readme_content = (
    "# EIS Analytics Framework\n\n"
    "Framework para análise automática de dados de Espectroscopia de Impedância "
    "Eletroquímica (EIS), com extração de métricas físicas, análise multivariada "
    "(PCA) e inferência da aplicação tecnológica mais adequada para cada amostra.\n\n"
    "## Objetivo\n"
    "- Processar qualquer número de amostras de EIS\n"
    "- Extrair parâmetros físicos sem forçar circuitos equivalentes\n"
    "- Comparar materiais de forma objetiva\n"
    "- Classificar aplicação provável:\n"
    "  - Bateria\n"
    "  - Supercapacitor\n"
    "  - Célula eletroquímica genérica\n"
    "  - Célula fotoeletroquímica / fotovoltaica\n\n"
    "## Estrutura do Projeto\n"
    "eis_analytics/\n"
    "├── data/\n"
    "│   ├── raw/\n"
    "│   └── processed/\n"
    "├── src/\n"
    "├── outputs/\n"
    "│   ├── tables/\n"
    "│   └── figures/\n"
    "└── main.py\n\n"
    "## Instalação\n"
    "Execute o script de configuração do ambiente:\n\n"
    "bash setup_env.sh\n"
    "source venv/bin/activate\n\n"
    "## Execução\n"
    "Coloque os arquivos de EIS em data/raw/ e execute:\n\n"
    "python main.py\n\n"
    "## Saídas\n"
    "- Tabela com propriedades físicas extraídas\n"
    "- Scores de PCA\n"
    "- Classificação automática de aplicação\n\n"
    "## Metodologia\n"
    "- Capacitância efetiva dependente da frequência\n"
    "- Resistência série (Rs) e resistência de polarização (Rp)\n"
    "- Energia acumulada\n"
    "- Constante de tempo dominante\n"
    "- PCA interpretado fisicamente\n\n"
    "## Contexto Acadêmico\n"
    "Projeto desenvolvido para análise de materiais eletroquímicos "
    "em contexto de iniciação científica.\n"
)

with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)

print("README.md criado com sucesso.")
