"""LaTeX booktabs table exporter for scientific manuscripts.

Generates ``.tex`` files containing publication-quality tables that can be
``\\input{}``-ed directly into an academic paper.  Two table types are
supported:

1. **Circuit fitting parameters** — one row per sample, columns = circuit
   element values with ± uncertainties.
2. **EIS feature ranking** — one row per sample, columns = Score, Rank,
   Rs, Rp, C_dl, σ_W (Warburg), and other derived features.

Both tables use the ``booktabs`` package (``\\toprule`` / ``\\midrule`` /
``\\bottomrule``) and ``siunitx`` for number formatting where available.

The exporter also accepts plain ``raw_eis`` DataFrames and writes a simple
frequency/impedance table in that case.

Output format
-------------
::

    \\begin{table}[htbp]
      \\centering
      \\caption{...}
      \\label{tab:...}
      \\begin{tabular}{lSSS}
        \\toprule
        Sample & {Z'} & {-Z''} & {|Z|} \\\\
        \\midrule
        Sample A & 12.3 & 3.1 & 12.7 \\\\
        ...
        \\bottomrule
      \\end{tabular}
    \\end{table}
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import List, Optional

import pandas as pd

from .base import EISExporter, ExportError

logger = logging.getLogger(__name__)

__all__ = ["LaTeXExporter", "export_circuit_table_latex", "export_ranking_latex"]

# Characters that need escaping in LaTeX
_LATEX_SPECIAL = re.compile(r"([&%$#_{}~^\\])")


def _tex_escape(text: str) -> str:
    """Escape LaTeX special characters in plain text."""

    def _replace(m: re.Match) -> str:
        ch = m.group(1)
        mapping = {
            "&": r"\&",
            "%": r"\%",
            "$": r"\$",
            "#": r"\#",
            "_": r"\_",
            "{": r"\{",
            "}": r"\}",
            "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}",
            "\\": r"\textbackslash{}",
        }
        return mapping.get(ch, ch)

    return _LATEX_SPECIAL.sub(_replace, str(text))


def _fmt_val(val: object, decimals: int = 4) -> str:
    """Format a numeric value for LaTeX siunitx, or return escaped string."""
    try:
        f = float(val)  # type: ignore[arg-type]
        if abs(f) >= 1e4 or (abs(f) < 1e-3 and f != 0.0):
            return f"{f:.{decimals}e}"
        return f"{f:.{decimals}f}"
    except (TypeError, ValueError):
        return _tex_escape(str(val))


class LaTeXExporter(EISExporter):
    """Export EIS raw spectrum data as a LaTeX booktabs frequency table.

    For circuit fitting parameters / ranking tables, use the standalone
    functions :func:`export_circuit_table_latex` and
    :func:`export_ranking_latex`.
    """

    DEFAULT_EXTENSION = ".tex"
    FORMAT_NAME = "LaTeX booktabs (.tex)"

    def export_dataframe(
        self,
        df: pd.DataFrame,
        out_path: Path,
        *,
        sample_name: str = "",
        extra_meta: dict | None = None,
    ) -> Path:
        """Write a frequency/impedance table for a single EIS spectrum.

        Columns written: Frequency (Hz), Z' (Ω), -Z'' (Ω), |Z| (Ω).
        """
        data = self._validate_df(df).copy()
        data.dropna(subset=["frequency", "zreal", "zimag"], inplace=True)
        if data.empty:
            raise ExportError(f"No valid data rows for '{sample_name}'.")

        data["|Z|"] = (data["zreal"] ** 2 + data["zimag"] ** 2) ** 0.5
        neg_zimag = -data["zimag"]

        caption = _tex_escape(sample_name or "EIS Spectrum")
        label = "tab:" + re.sub(r"[^a-zA-Z0-9]", "_", sample_name or "eis")

        rows: List[str] = []
        for _, row in data.iterrows():
            rows.append(
                f"    {_fmt_val(row['frequency'], 4)} & "
                f"{_fmt_val(row['zreal'], 4)} & "
                f"{_fmt_val(neg_zimag[row.name], 4)} & "
                f"{_fmt_val(row['|Z|'], 4)} \\\\"
            )

        tex = _build_table(
            caption=caption,
            label=label,
            col_spec="SSSS",
            headers=[
                r"$f$ / \si{\hertz}",
                r"$Z'$ / \si{\ohm}",
                r"$-Z''$ / \si{\ohm}",
                r"$|Z|$ / \si{\ohm}",
            ],
            rows=rows,
            note=f"Generated by IonFlow Pipeline — {self._now_str()}",
        )

        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(tex, encoding="utf-8")
        return out_path


# ---------------------------------------------------------------------------
# Standalone table builders for circuit and ranking data
# ---------------------------------------------------------------------------


def export_circuit_table_latex(
    circuit_table: pd.DataFrame,
    out_path: str | Path,
    *,
    caption: str = "Circuit fitting parameters",
    label: str = "tab:circuit_params",
    decimals: int = 4,
) -> Path:
    """Write a circuit fitting parameter table to a ``.tex`` file.

    Parameters
    ----------
    circuit_table : pd.DataFrame
        The ``EISResult.circuit_table`` DataFrame.  Index or first column
        should be the sample name.
    out_path : str or Path
        Destination ``.tex`` file.
    caption : str
        Table caption inserted into ``\\caption{}``.
    label : str
        LaTeX ``\\label{}`` identifier.
    decimals : int
        Significant digits for numeric values.

    Returns
    -------
    Path
        Path of the written file.
    """
    if circuit_table is None or circuit_table.empty:
        raise ExportError("circuit_table is empty — nothing to export.")

    df = circuit_table.reset_index()
    # Use first column as the sample identifier
    id_col = df.columns[0]

    # Select numeric columns only (+ the id column)
    num_cols = [c for c in df.columns[1:] if pd.api.types.is_numeric_dtype(df[c])]
    cols_to_show = [id_col] + num_cols

    headers = [_tex_escape(str(c)) for c in cols_to_show]
    col_spec = "l" + "S" * len(num_cols)

    rows: List[str] = []
    for _, row in df[cols_to_show].iterrows():
        cells = [_tex_escape(str(row[id_col]))] + [
            _fmt_val(row[c], decimals) for c in num_cols
        ]
        rows.append("    " + " & ".join(cells) + " \\\\")

    tex = _build_table(
        caption=caption,
        label=label,
        col_spec=col_spec,
        headers=headers,
        rows=rows,
    )

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex, encoding="utf-8")
    return out_path


def export_ranking_latex(
    ranked_df: pd.DataFrame,
    out_path: str | Path,
    *,
    caption: str = "EIS feature ranking",
    label: str = "tab:eis_ranking",
    max_cols: int = 10,
    decimals: int = 3,
) -> Path:
    """Write the EIS ranking DataFrame as a booktabs table.

    Parameters
    ----------
    ranked_df : pd.DataFrame
        The ``EISResult.ranked_df`` DataFrame.
    out_path : str or Path
        Destination ``.tex`` file.
    caption : str
        Table caption.
    label : str
        LaTeX label.
    max_cols : int
        Maximum number of feature columns to include (avoids very wide tables).
    decimals : int
        Decimal places for numeric values.

    Returns
    -------
    Path
        Path of the written file.
    """
    if ranked_df is None or ranked_df.empty:
        raise ExportError("ranked_df is empty — nothing to export.")

    df = ranked_df.reset_index()
    id_col = df.columns[0]
    all_cols = df.columns.tolist()

    # Prefer Rank, Score first, then numeric columns up to max_cols
    priority = [c for c in ["Rank", "Score"] if c in all_cols]
    rest = [
        c
        for c in all_cols
        if c not in priority and c != id_col and pd.api.types.is_numeric_dtype(df[c])
    ]
    selected = [id_col] + priority + rest[: max_cols - len(priority) - 1]

    headers = [_tex_escape(str(c)) for c in selected]
    num_cols_names = [c for c in selected if c != id_col]
    col_spec = "l" + "S" * len(num_cols_names)

    rows: List[str] = []
    for _, row in df[selected].iterrows():
        cells = [_tex_escape(str(row[id_col]))] + [
            _fmt_val(row[c], decimals) for c in num_cols_names
        ]
        rows.append("    " + " & ".join(cells) + " \\\\")

    tex = _build_table(
        caption=caption,
        label=label,
        col_spec=col_spec,
        headers=headers,
        rows=rows,
    )

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex, encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------------


def _build_table(
    caption: str,
    label: str,
    col_spec: str,
    headers: List[str],
    rows: List[str],
    note: Optional[str] = None,
) -> str:
    """Assemble a full booktabs ``table`` environment as a string."""
    header_row = " & ".join(f"{{{h}}}" for h in headers) + " \\\\"

    note_block = ""
    if note:
        note_block = (
            "\n  \\begin{tablenotes}\\small\n"
            f"    \\item {_tex_escape(note)}\n"
            "  \\end{tablenotes}"
        )
        # Wrap in threeparttable if we have a note
        inner = (
            "  \\begin{threeparttable}\n"
            f"  \\begin{{tabular}}{{{col_spec}}}\n"
            "    \\toprule\n"
            f"    {header_row}\n"
            "    \\midrule\n" + "\n".join(rows) + "\n    \\bottomrule\n"
            "  \\end{tabular}" + note_block + "\n  \\end{threeparttable}"
        )
    else:
        inner = (
            f"  \\begin{{tabular}}{{{col_spec}}}\n"
            "    \\toprule\n"
            f"    {header_row}\n"
            "    \\midrule\n" + "\n".join(rows) + "\n    \\bottomrule\n"
            "  \\end{tabular}"
        )

    return (
        "% Generated by IonFlow Pipeline — src/export/latex.py\n"
        "% Required packages: booktabs, siunitx, threeparttable (optional)\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        f"  \\caption{{{_tex_escape(caption)}}}\n"
        f"  \\label{{{label}}}\n" + inner + "\n\\end{table}\n"
    )
