"""BioLogic EC-Lab EIS file parser (.mpr and .txt/.csv exports).

BioLogic instruments produce two file types:

1. **Binary .mpr** — proprietary binary format.  Parsing requires the
   ``galvani`` library (``pip install galvani``).  If ``galvani`` is not
   installed, the parser falls back gracefully with a helpful error.

2. **Text .mpt / .txt export** — tab-separated ASCII generated by EC-Lab's
   "Export to text" function.  This format is always supported without
   extra dependencies.

Typical .mpt header::

    EC-Lab ASCII FILE
    Nb header lines : 67
    ...
    freq/Hz  Re(Z)/Ohm  -Im(Z)/Ohm  |Z|/Ohm  Phase(Z)/deg  ...
    100000   4.56       0.54        4.59      6.79           ...

The parser auto-detects which format is being read.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from .base import ParsedEIS, PotentiostatParser

logger = logging.getLogger(__name__)

# Magic bytes at the start of every .mpr binary file
_MPR_MAGIC = b"BIO-LOGIC MODULAR FILE"
# Magic text at start of .mpt ASCII export
_MPT_MAGIC = "EC-Lab ASCII FILE"


class BioLogicParser(PotentiostatParser):
    """Parser for BioLogic EC-Lab EIS files (.mpr binary or .mpt/.txt text)."""

    EXTENSIONS = [".mpr", ".mpt", ".txt"]

    @classmethod
    def can_parse(cls, path: str | Path) -> bool:
        p = Path(path)
        if p.suffix.lower() == ".mpr":
            try:
                with open(p, "rb") as fh:
                    return fh.read(len(_MPR_MAGIC)) == _MPR_MAGIC
            except OSError:
                return False
        if p.suffix.lower() in (".mpt", ".txt"):
            try:
                with open(p, encoding="utf-8", errors="replace") as fh:
                    first = fh.readline()
                return _MPT_MAGIC in first
            except OSError:
                return False
        return False

    def parse(self, path: str | Path) -> ParsedEIS:
        """Parse a BioLogic EIS file."""
        path = Path(path)

        if path.suffix.lower() == ".mpr":
            return self._parse_mpr(path)
        return self._parse_mpt(path)

    # ------------------------------------------------------------------
    # Binary .mpr (requires galvani)
    # ------------------------------------------------------------------

    def _parse_mpr(self, path: Path) -> ParsedEIS:
        try:
            from galvani import BioLogic  # type: ignore[import]
        except ImportError:
            raise ImportError(
                "The 'galvani' package is required to read BioLogic .mpr files.\n"
                "Install it with:  pip install galvani\n"
                "Alternatively, export the file as .mpt from EC-Lab software."
            )

        mpr = BioLogic.MPRfile(str(path))
        df_raw = pd.DataFrame(mpr.data)

        col_map = _biologic_column_map(df_raw.columns.tolist())
        df = _build_dataframe(self, df_raw, col_map, path.name)

        meta = {
            "technique": getattr(mpr, "technique", ""),
            "version": getattr(mpr, "version", ""),
        }
        result = ParsedEIS(
            data=df,
            source_file=str(path.resolve()),
            instrument="BioLogic EC-Lab (binary .mpr)",
            extra_meta=meta,
        )
        result.validate()
        return result

    # ------------------------------------------------------------------
    # Text .mpt / .txt export
    # ------------------------------------------------------------------

    def _parse_mpt(self, path: Path) -> ParsedEIS:
        content = path.read_text(encoding="utf-8", errors="replace")
        lines = content.splitlines()

        # Find number of header lines
        nb_header = _find_mpt_header_count(lines)
        meta = _parse_mpt_header(lines[:nb_header])

        # The line just before data is the column header
        header_line = lines[nb_header - 1]
        col_names = [c.strip() for c in header_line.split("\t")]

        # Parse data rows
        data_rows = []
        for line in lines[nb_header:]:
            stripped = line.strip()
            if not stripped:
                continue
            parts = stripped.split("\t")
            if len(parts) >= 3:
                data_rows.append(parts)

        if not data_rows:
            raise ValueError(f"No data rows found in BioLogic .mpt file: {path.name}")

        df_raw = pd.DataFrame(data_rows, columns=col_names[: len(data_rows[0])])
        col_map = _biologic_column_map(df_raw.columns.tolist())
        df = _build_dataframe(self, df_raw, col_map, path.name)

        result = ParsedEIS(
            data=df,
            source_file=str(path.resolve()),
            instrument="BioLogic EC-Lab (text .mpt)",
            extra_meta=meta,
        )
        result.validate()
        return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _find_mpt_header_count(lines: list) -> int:
    """Return the number of header lines in a .mpt file."""
    for line in lines[:10]:
        if "Nb header lines" in line:
            try:
                return int(line.split(":")[-1].strip())
            except ValueError:
                pass
    # Fallback: scan for the column header line
    for i, line in enumerate(lines):
        lower = line.lower()
        if "freq" in lower and ("re(z)" in lower or "z'" in lower or "zreal" in lower):
            return i + 1
    return 1


def _parse_mpt_header(header_lines: list) -> dict:
    """Extract key-value metadata from .mpt header lines."""
    meta: dict = {}
    for line in header_lines:
        if ":" in line:
            key, _, val = line.partition(":")
            meta[key.strip()] = val.strip()
    return meta


def _biologic_column_map(columns: list) -> dict:
    """Map BioLogic column names to standard keys."""
    col_map: dict = {}
    lower = [c.lower().replace(" ", "") for c in columns]

    for i, c in enumerate(lower):
        if col_map.get("freq") is None and c in (
            "freq/hz",
            "frequency/hz",
            "freq",
            "f/hz",
        ):
            col_map["freq"] = columns[i]
        elif col_map.get("zreal") is None and c in (
            "re(z)/ohm",
            "zreal/ohm",
            "z'/ohm",
            "re(z)",
            "zreal",
            "z'",
        ):
            col_map["zreal"] = columns[i]
        elif col_map.get("zimag") is None and c in (
            "-im(z)/ohm",
            "-imag(z)/ohm",
            "z''/ohm",
            "-im(z)",
            "zimag",
            "-z''",
            "imag(z)/ohm",
        ):
            col_map["zimag"] = columns[i]
        elif col_map.get("zmag") is None and c in ("|z|/ohm", "z/ohm", "|z|", "zmag"):
            col_map["zmag"] = columns[i]
        elif col_map.get("phase") is None and c in (
            "phase(z)/deg",
            "phz/deg",
            "phase",
            "theta",
        ):
            col_map["phase"] = columns[i]

    return col_map


def _build_dataframe(
    parser: PotentiostatParser,
    df_raw: pd.DataFrame,
    col_map: dict,
    filename: str,
) -> pd.DataFrame:
    """Build standardised DataFrame from raw data and column map."""
    if "freq" not in col_map or "zreal" not in col_map or "zimag" not in col_map:
        raise ValueError(
            f"Could not identify Freq/Zreal/Zimag columns in {filename}.\n"
            f"Found columns: {list(df_raw.columns)}"
        )

    df = pd.DataFrame()
    df["frequency"] = parser._to_numeric(df_raw[col_map["freq"]])
    df["zreal"] = parser._to_numeric(df_raw[col_map["zreal"]])
    df["zimag"] = parser._to_numeric(df_raw[col_map["zimag"]])

    if col_map.get("zmag"):
        df["|Z|"] = parser._to_numeric(df_raw[col_map["zmag"]])
    if col_map.get("phase"):
        df["phase_deg"] = parser._to_numeric(df_raw[col_map["phase"]])

    df = df.dropna(subset=["frequency", "zreal", "zimag"])
    df = parser._enforce_zimag_convention(df)
    return df.reset_index(drop=True)
